# -*- coding: utf-8 -*-
"""Copy of Welcome to Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0EZFT1Z-O6r5b5PmveAaA-krGQIsDwp
"""

#pip install beautifulsoup4

#pip install requests

#pip install pandas
import requests
import pandas as pd
from bs4 import BeautifulSoup

url="https://www.msamb.com/Home/Index"
r = requests.get(url)
# print(r)

soup = BeautifulSoup(r.text,"lxml")
# print(soup)

table = soup.find("table",class_ ="table")
# print(table)
#title = table.find_all("th")
# print(title)

#header=[]

#for i in title:
#  name = i.text
#  header.append(name)

#df = pd.DataFrame(columns=header)
#print(df)

rows = table.find_all("tr")
print(rows)

for i in rows[1:]:
    data = i.find_all("td")
    row = [tr.text for tr in data ]
    # l = len(df)
    # df.loc[l] = row 
    print(row)

